### ISSUE TITLE
Unknown mod NaN on page 1

### ISSUE THREAD

**Issue by ChaosMarc** [youdz/d2-stash-organizer#11]
I just found a pair of Sigon's boots that can't be parsed:

Failed to parse K's undefined at row 12, column 0: Unknown mod NaN on page 1

[Liselle.zip](https://github.com/youdz/d2-stash-organizer/files/6876945/Liselle.zip)

**Comment by youdz** [comment]
Fixed.

Thanks for the stash file, the bug was actually a 1 in 65536 so it would have been troublesome to debug blind. 👍
