### ISSUE TITLE
Feature Request: First and last page buttons

### ISSUE THREAD

**Issue by ChaosMarc** [youdz/d2-stash-organizer#13]
Hey youdz,

I hope you don't mind me throwing around some of the ideas I have while using your awesome tool.

As I'm not using the organizing feature (because I'm pedantic and want my own sorting order 👼) I have more than 300 pages. I wanted to check something on the last page and noticed that I had to klick over 30 times to get there. As you previously said you pay much attention to UX and accessibility I thought that this would be something you wanted to implement ;)

**Comment by youdz** [comment]
Done. 👍
