### ISSUE TITLE
Bug: Milabrega's Orb 150% Perfect 😂

### ISSUE THREAD

**Issue by ChaosMarc** [youdz/d2-stash-organizer#15]
I guess there must be something wrong the the perfection computation of Milabrega's Orb'. Everyone of them I could find are 150% perfect.

![image](https://user-images.githubusercontent.com/1343751/127685045-730602e3-949e-4b1b-9265-0834aecd11a3.png)
[Amazing.zip](https://github.com/youdz/d2-stash-organizer/files/6908977/Amazing.zip)

**Comment by youdz** [comment]
Fixed in #20.
