### ISSUE TITLE
Feature Request: Storing multiple stashes + Chars

### ISSUE THREAD

**Issue by ChaosMarc** [youdz/d2-stash-organizer#17]
This one is a bit bigger 😇 

Use case: I have multiple chars that I regularly play alternately. Most items are stored in my shared stash. Every now and then I put some items in the personal stash of a char. The chars wear some unique/set items that I only possess once. 

Idea: Instead of only having one uploaded stash file active at a time I propose some kind of stash/char management page that replaces the Organize tab. In my mind I have some kind of table there in which every uploaded (stash-)file is listed with the timestamp of the upload, a sort/download button and a delete button. If you could add the possibility to upload the save file (d2s) itself chars would be listed there too (without the sort button ofc, only download and delete). Additionally the "My Stash" (maybe "My Collection" would be more appropriate) tab would have to be extended to show tabs (or similar) for shared, personal and chars. When filtering for specific items, there should be the option to select where to search (everywhere, only shared stash, specific char(s)). The upload feature should allow selecting multiple files at once for more convenience. 

Benefit: The Grail tracker would show a more complete picture of the actual collection. You could quickly find the current location of specific items without having to start a game with all chars and check their inventory/private stash.

**Comment by youdz** [comment]
Yeah, this has definitely been on my mind for a bit. My main concern is that you could actually lose items this way with the organizer, if you are not diligent about updating all char files all the time. There would be no way for me to guard against. That's my biggest concern, and I don't want to lose the trust of players if they lose the Enigma they've been moving around between characters.

So I've been mulling over how to:
- Not upload a single stash, but select the entire folder instead and let the tool grab the shared stash and every personal stash in there.
- Download a ZIP of all stashes or some other multi-file single download after organizing.

Browser support isn't great for that right now, so I'll need some quiet time to research and find some innovative solution. I like the challenge. :)

**Comment by youdz** [comment]
Done. Character files are now fully supported, along with all the extra features they needed (like more granular transfer of items).
