### ISSUE TITLE
Page locks on upload

### ISSUE THREAD

**Issue by deerslayer82** [youdz/d2-stash-organizer#27]
Hi, I uploaded my .sss file but the page locks. File attached.
[_LOD_SharedStashSave.zip](https://github.com/youdz/d2-stash-organizer/files/7084008/_LOD_SharedStashSave.zip)

**Comment by deerslayer82** [comment]
I tested some personal stash files for the characters that use the shared one and those work fine.

**Comment by youdz** [comment]
I think I have fixed the cause of that bug 5 times already (item id containing one of the save file tags used to delimit items and pages), and every time a new slightly different variation comes up.

I finally just refactored the code to avoid the problem altogether. It's now less readable and a bit heavier, but I think it'll squash all the variations of this bug for good.

I just tested your save file, it works fine now.
