### ISSUE TITLE
Bug: no page numbers

### ISSUE THREAD

**Issue by duftin** [youdz/d2-stash-organizer#28]
Recently, when I load my shared stash, there are no page numbers:
![no page numbers](https://user-images.githubusercontent.com/41693096/132140839-28ce2128-ced7-4587-bd5e-61cb438ac43f.png)
If I organize my stash and leave the first X pages unorganized, the unorganized pages will remain without numbers which will cause an error that prevents me from playing my characters. If I organize all pages, the pages will be numbered, but when I load the same file (even without loading the game first/modifying the file), all pages will be without numbers like the above screenshot.

I admit I've been messing around with hero editor to make some goofy items, so it's possible I accidentally caused this on my end. I've included my shared stash file if you want to take a look.
[_LOD_SharedStashSave.zip](https://github.com/youdz/d2-stash-organizer/files/7112330/_LOD_SharedStashSave.zip)

**Comment by youdz** [comment]
Oops, my bad, off-by-one error after the fix from yesterday. Give me a minute.

**Comment by youdz** [comment]
Fixed and deployed. 😄 

>I admit I've been messing around with hero editor to make some goofy items, so it's possible I accidentally caused this on my end.

The parser has actually really good support for hacked items. The problem is mods which modify the game files (like PD2). As long as you create crazy items with the basic hero editor, which uses plain D2 attributes, I think they'll all be fine.
