### ISSUE TITLE
Quality filter is missing a runeword option

### ISSUE THREAD

**Issue by ChaosMarc** [youdz/d2-stash-organizer#29]
see the title. shouldn't be hard to add. maybe I will look into in myself

**Comment by youdz** [comment]
Haha, I'm actually implementing this right now on the multi-character branch, as I was refactoring the quality filter anyway. 

Filters I have so far:
- All
- Normal
- Superior
- Magic
- Rare
- Unique
- Set
- word
- Crafted
- Non-equipment

Yes, I got rid of the "Low quality filter" as I'm not actually sure it's ever useful, and I want to declutter when possible. Note that "Normal" returns both low quality and superior items too, pretty much all white and gray equipments.

Depending on how much progress I make on the multi-character branch, I might just port this to `main` if I can see it taking too long.

**Comment by ChaosMarc** [comment]
Great news :) don't worry about bringing this to `main`. At least for me this has no priority 😇

**Comment by youdz** [comment]
Released along with multi-stash support.
