### ISSUE TITLE
Item filter can't find socketed items

### ISSUE THREAD

**Issue by ChaosMarc** [youdz/d2-stash-organizer#30]
Since https://github.com/youdz/d2-stash-organizer/issues/19 socketed unique items (aka the rainbow facets) count to the grail tracker. I think if that's the case, they should also be findable through the item filter. I would also be nice to find items with a specific rune inside (e.g. MF gear with ISTs socketed)

**Comment by youdz** [comment]
Nice, back-to-back features I anticipated and have been working on in the new version (separate branch while working as it's a major undertaking). 

Already added to the multi-char branch: https://github.com/youdz/d2-stash-organizer/blob/multi-char/src/scripts/items/post-processing/postProcessItem.ts#L48

Same as the other issue, depending on how much progress I make on the multi-character branch I might just port this to main if I can see it taking too long.

**Comment by ChaosMarc** [comment]
I already took a peak into your new branch. Looks really nice :) 

Are you planning (on a later date) on adding d2s save file support too? I started a very rudimentary approach (https://github.com/ChaosMarc/d2-stash-organizer/tree/d2s-parsing) but didn't get very far. This get's complicated really fast. There is a working library for this at https://github.com/dschu012/d2s though...

**Comment by youdz** [comment]
Yes, the goal is to kind of de-couple this from PlugY, keeping the PlugY stash support but also working with just good old mules.

I'm not sure how hard parsing d2s will be, as I'm actually not interested in anything but items right now. So I could skip over directly to the items portion, and just add support for items that are equipped, in inventory, in the belt, etc.

**Comment by ChaosMarc** [comment]
sadly skipping the meta data is not really an option, as the length of data before the actual items start is variable and depends on stuff you have to parse first (char attributes and skills). Only the header with char meta data / quest status / waypoints at the start of the file is fixed in length and can be skipped.

**Comment by youdz** [comment]
Released along with multi-stash support. Next step (not sure when), .d2s support!
