### ISSUE TITLE
Error: failed to parse [item]

### ISSUE THREAD

**Issue by duftin** [youdz/d2-stash-organizer#33]
Hi, I got the following error when uploading my stashes:
![soul thirst](https://user-images.githubusercontent.com/41693096/132994158-d7d3198b-c67e-404e-b655-0a5b3bb4a526.png)

I went into the character's stash and deleted the item ("Soul Thirst" rare assassin claw) and now the stashes load problem-free.
I've attached the character's stash file so you can see for yourself what the issue is.

[Garthly.zip](https://github.com/youdz/d2-stash-organizer/files/7149865/Garthly.zip)

(I love this tool, by the way. Thanks!)

**Comment by youdz** [comment]
Fixed, thanks for the report. :)
