### ISSUE TITLE
Bug: Civerb's Ward 1500% Perfect

### ISSUE THREAD

**Issue by cyhyraethz** [youdz/d2-stash-organizer#34]
![Screenshot from 2021-09-15 10-45-06](https://user-images.githubusercontent.com/45051951/133483568-c0b89965-7834-4c39-a0df-29febfa4b9d5.png)

**Comment by youdz** [comment]
Ah right, looks like I introduced a bug with set item modifiers for perfection score. It's fixed now, thanks for the report. :)
