### ISSUE TITLE
Bug: PlugY stash buttons broke

### ISSUE THREAD

**Issue by DaveJK** [youdz/d2-stash-organizer#36]
My first time using this organizer and it's amazing, thank you. My problem is when I downloaded the SharedStashSave my PlugY stash buttons no longer work properly. The 'Next Index(10 page)' and 'Next Index(100)' go by 1 page and 3 pages respectively.

Also, I'm not sure if I am missing a setting somewhere but the stash pages aren't numbered in game. They show as '# Rejuvs', '# Respecs', etc so it's hard to find "Goblin Toe on page 51" with no page numbers, along with the stash buttons not working mentioned above.

Maybe I just need to clear the game out and reinstall PlugY fresh but I thought I would ask here first in case it was a bug with the organizer. Thanks for any help

**Comment by ChaosMarc** [comment]
From the readme:
> It names pages nicely, adds indices between sections

The buttons didn't break but the indices to which the buttons point have been moved to allow jumping to every item type via button click and not the default 10/100 pages. You can change the indices yourself by clicking on the name of a page (there is even an in game info text when hovering the name). By doing so the color of the page name will change. Sadly there is no way to reset all indices back to default. So either you go back to a previous backup or try to live with the new indeces

**Comment by DaveJK** [comment]
> You can change the indices yourself by clicking on the name of a page (there is even an in game info text when hovering the name). 

Is this the name in game you are referring to click on? It doesn't do anything for me when I click on it
![D2SE_v9eU9xfHHR](https://user-images.githubusercontent.com/24943733/134119853-c44d2eea-f744-4f7e-a9f6-74c5408db93f.png)

**Comment by ChaosMarc** [comment]
Which version of plugy are you using? This is a v14.00+ feature

**Comment by DaveJK** [comment]
> Which version of plugy are you using? This is a v14.00+ feature

My internet went out but I finally updated PlugyY from the previous version to v14+ and the pages now have numbers instead of #, colored text that isn't just red, and an infobox on hover. Thanks for your help

**Comment by youdz** [comment]
Thanks so much @ChaosMarc for helping people out during my long silences. 👍 

Yes, this looked like a PlugY version issue, with PlugY supporting latest D2 (outside of Resurrected), there is little reason to be on an older version. So I"m not going to spend too much time trying to be compatible with older PlugY versions.
