### ISSUE TITLE
Failed to parse item

### ISSUE THREAD

**Issue by Tiegerkatzi** [youdz/d2-stash-organizer#4]
Hello,

I get the message "Failed to parse item with code Hù at row 2, column 8 on page 1"

I can do nothing with the code. It´s a small charm but it is on Page 1 at the top left corner. So it should be column 1 row 1.

https://www.dropbox.com/s/7phc3833jmnsx68/_LOD_SharedStashSave_1.sss?dl=0

**Comment by youdz** [comment]
Found the bug shortly after posting on the other issue, it's fixed and deployed. 👍
