### ISSUE TITLE
Feature Request: option for different UI text

### ISSUE THREAD

**Issue by AlexFullmoon** [youdz/d2-stash-organizer#45]
This may sound like a heresy, but I always found Exocet font to be nigh-unreadable. I am used to it in game, but everywhere else it is pure torment. Site also has just a bit too small font size for me.

Is there a possibility to add a switch to some plain boring generic sans-serif?

**Comment by youdz** [comment]
There you go, check out the newly added Settings section.

It also persists across refreshes and closing/reopening the app, because I'm guessing you don't want to reselect it every time.
