### ISSUE TITLE
Unknown mod strength

### ISSUE THREAD

**Issue by duftin** [youdz/d2-stash-organizer#8]
Hi, I'm currently getting the error "[unknown mod strength](https://i.imgur.com/lf3fi32.png)" when I try to upload my shared stash file.
![error](https://user-images.githubusercontent.com/41693096/126912386-3e9e1609-4e48-4e59-88a2-10ba4c5d1efa.png)
(Thanks for making this app, by the way!)

**Comment by zepcheese** [comment]
Yep, just hit this myself...

**Comment by youdz** [comment]
Oops, my bad. Little bug on a strength because it's the very first stat in the game file. Fixed now. 🙂
